#!/usr/bin/env ruby

config_file = File.join(File.expand_path('~'), '.jwtgenrc')
if File.exist?(config_file)
  default_argv = File.read(config_file).split
  ARGV.unshift(*default_argv)
end

require 'optparse'

options = {}
OptionParser.new do |opts|
  ALGORITHMS = %w(HS256 HS512256 HS384 HS512)
  opts.banner = 'Usage: jwtgen [options] [arguments]
        arguments                    JWT payload key-value pairs, e.g. key1 value1 key2 value2 key3 value3
                                     Required inputs (keys) are user_id and email.'
  opts.on('--key KEY', 'HMAC secret key') do |key|
    options[:key] = key
  end
  opts.on('--algorithm ALGORITHM', ALGORITHMS, 'Cryptographic hash algorithm, one of: none, HS256 HS512256 HS384 HS512') do |algorithm|
    options[:algorithm] = algorithm
  end
end.parse!

ARGV << '' if ARGV.size % 2 == 1
options[:payload] = Hash[*ARGV].inject({}) { |acc,(k,v)| acc[k.to_sym] = v; acc }

require 'jwtgen'
require 'clipboard'

begin
  Clipboard.copy Jwtgen.new(options).encode
  puts 'The JWT has been copied to your clipboard!'
  exit
rescue ArgumentError => e
  abort("** Error occurred: #{e.message}. Get help: jwtgen --help")
end
